const express = require("express")
require("dotenv").config()
const cors = require("cors")
const app = express()
const path = require("path")
const fileupload = require("express-fileupload")
app.use(fileupload())
app.use(cors())
app.use(express.json())
app.use("/images",express.static("./controllers/uploads"))
app.use(express.static(path.join(__dirname,"/client/dist")))
const connectDB = require("./config/db") 
const router = require("./routes/mainRouter")
connectDB()
app.use(router)
app.get("*",(req,res)=>{
    res.sendFile((path.join(__dirname,"/client/dist/index.html")))
})
app.listen(process.env.PORT || 3002)