name: Node.js CI

on:
  push:
    branches: [ "aniket_dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 20.x
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
        cache: 'npm'
    - run: npm install
    - run: npm run build
    - name: Create and checkout deploy branch
      run: |
        git config --global user.email "aniket.sharma.4509@gmail.com"
        git config --global user.name "Aniket Sharma"
        git checkout -b deploy
        git add client/dist
        git commit -m "Add build artifacts"
        git push origin deploy
